project:
  type: website
  output-dir: "."

website:
  title: "McAndrew Bean"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Homework
      - href: danl200-hw5-bean-mcandrew.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© McAndrew Bean, 2023"

format:
  html:
    theme: 
      light: tango
      dark: tango
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
